import type { OrbMode, OrbState } from './types';

/** A semantic state name that has a matching direct import entry point. */
export type LoaderStateName = Exclude<OrbState, OrbMode>;

/**
 * Single source of truth for the public state names and their pure geometry builders.
 *
 * The runtime resolver, playground metadata, direct-entry verification and future documentation
 * generation all derive from this registry rather than maintaining independent state lists.
 */
export const STATE_TO_MODE: Record<LoaderStateName, OrbMode> = {
  working: 'orbit',
  searching: 'scan',
  connecting: 'network',
  weaving: 'weave',
  shaping: 'morph',
  listening: 'wave',
  breathing: 'pulse',
  composing: 'ribbon',
  solving: 'cube',
  observing: 'halo',
  dreaming: 'tunnel',
  charging: 'swarm',
  flowing: 'knot',
  awakening: 'nova',
  coding: 'circuit',
  transcending: 'portal',
  singing: 'aurora',
  growing: 'helix',
  blooming: 'flower',
  wandering: 'fireflies',
  decoding: 'matrix',
  calibrating: 'gyroscope',
  attracting: 'magnet',
  shattering: 'shards',
  crystallizing: 'crystal',
  constellating: 'constellation',
  folding: 'origami',
  echoing: 'echo',
  balancing: 'mobile',
  weathering: 'vortex',
  mapping: 'atlas',
  forging: 'forge',
  orbiting: 'satellites',
  racing: 'comet',
  bubbling: 'bubbles',
  spinning: 'pinwheel',
  electrifying: 'plasma',
  flocking: 'flock',
  throbbing: 'beats',
  cascading: 'cascade',
  spiraling: 'galaxy',
  juggling: 'juggle',
  eclipsing: 'eclipse',
  resonating: 'resonance',
  condensing: 'condense',
  dispersing: 'disperse',
  prisming: 'prism',
  levitating: 'levitate',
  synchronizing: 'synchronize',
  unraveling: 'unravel',
  pondering: 'lattice',
  deducing: 'deduce',
  branching: 'branch',
  focusing: 'aperture',
  reflecting: 'mirror',
  weighing: 'scales',
  recalling: 'memory',
  tracing: 'trace',
  converging: 'converge',
  questioning: 'query',
  glimmering: 'glimmer',
  radiating: 'radiance',
  harmonizing: 'harmony',
  twinkling: 'twinkle',
  flickering: 'flicker',
  shimmering: 'shimmer',
  surfacing: 'surface',
  vibrating: 'vibrate',
  illuminating: 'illuminate',
  sparkling: 'sparkle',
  loading: 'spinner',
  buffering: 'buffer',
  typing: 'ellipsis',
  processing: 'process',
  synthesizing: 'reason',
  considering: 'consider',
  uploading: 'upload',
  queuing: 'queue',
  associating: 'associate',
  evaluating: 'evaluate',
  reasoning: 'cognition',
  exploring: 'explore',
  linking: 'link',
  resolving: 'resolve',
  imagining: 'imagine',
  'loading-bars': 'bars',
  progressing: 'progress',
  placeholder: 'skeleton',
  monitoring: 'waveform',
  checking: 'grid',
  tracking: 'radar',
  waiting: 'hourglass',
  pulsing: 'rings',
  signaling: 'signal',
  stepping: 'steps',
  streaming: 'stream',
  equalizing: 'equalizer',
  wiring: 'circuitboard',
  marqueeing: 'marquee',
  'orbiting-dots': 'orbitdots',
  charting: 'chart',
  plotting: 'plot',
  sampling: 'scatter',
  forecasting: 'forecast',
  metering: 'meter',
  heatmapping: 'heatmap',
  candlesticking: 'candles',
  graphing: 'graph',
  waterfalling: 'waterfall',
  clustering: 'clusters',
  indexing: 'index',
  benchmarking: 'benchmark',
  profiling: 'profile',
  binning: 'histogram',
  aggregating: 'aggregate',
  scrubbing: 'scrubber',
  telemetry: 'telemetryreadout',
  polling: 'poll',
  correlating: 'correlation',
  routing: 'flowmap',
  'bar-charting': 'barchart',
  comparing: 'comparison',
  accumulating: 'stacked',
  sequencing: 'timeline',
  transmitting: 'throughput',
  summarizing: 'donut',
  gauging: 'gauge',
  funneling: 'funnel',
  treemapping: 'treemap',
  areamapping: 'area',
  downloading: 'download',
  retrying: 'retry',
  scanning: 'scanner',
  compiling: 'compile',
  paginating: 'pagination',
  reconnecting: 'reconnect',
  sankeying: 'sankey',
  radaring: 'radarplot',
  scheduling: 'gantt',
  calendarizing: 'calendar',
  bulletting: 'bullet',
  boxing: 'boxplot',
  dispatching: 'dispatch',
  batching: 'batch',
  checkpointing: 'checkpoint',
  prioritizing: 'priority',
  verifying: 'verify',
  pendulating: 'pendulum',
  drifting: 'drift',
  raining: 'rain',
};

/** Ordered semantic state names used by consumers that need to enumerate the full library. */
export const LOADER_STATES = Object.freeze(Object.keys(STATE_TO_MODE) as LoaderStateName[]);

/** A named, ordered grouping of states for selectors, documentation and galleries. */
export interface LoaderCategory {
  /** Stable machine-readable category identifier. */
  readonly id: 'loaders' | 'systems' | 'data' | 'reasoning' | 'atmosphere' | 'motion';
  /** Human-readable category heading. */
  readonly label: string;
  /** States that belong to this category, in gallery order. */
  readonly states: readonly LoaderStateName[];
}

const loaderStates = [
  'loading',
  'buffering',
  'typing',
  'processing',
  'loading-bars',
  'progressing',
  'placeholder',
  'waiting',
  'pulsing',
  'downloading',
  'retrying',
  'scanning',
  'compiling',
  'paginating',
  'reconnecting',
] as const satisfies readonly LoaderStateName[];

const reasoningStates = [
  'pondering',
  'deducing',
  'branching',
  'focusing',
  'reflecting',
  'weighing',
  'recalling',
  'tracing',
  'converging',
  'questioning',
  'considering',
  'associating',
  'evaluating',
  'reasoning',
  'exploring',
  'linking',
  'resolving',
  'imagining',
  'prioritizing',
  'verifying',
] as const satisfies readonly LoaderStateName[];

const systemStates = [
  'uploading',
  'queuing',
  'signaling',
  'stepping',
  'wiring',
  'marqueeing',
  'orbiting-dots',
  'dispatching',
  'batching',
  'checkpointing',
] as const satisfies readonly LoaderStateName[];

const dataStates = [
  'monitoring',
  'checking',
  'tracking',
  'streaming',
  'equalizing',
  'charting',
  'plotting',
  'sampling',
  'forecasting',
  'metering',
  'heatmapping',
  'candlesticking',
  'graphing',
  'waterfalling',
  'clustering',
  'indexing',
  'benchmarking',
  'profiling',
  'binning',
  'aggregating',
  'scrubbing',
  'telemetry',
  'polling',
  'correlating',
  'routing',
  'bar-charting',
  'comparing',
  'accumulating',
  'sequencing',
  'transmitting',
  'summarizing',
  'gauging',
  'funneling',
  'treemapping',
  'areamapping',
  'sankeying',
  'radaring',
  'scheduling',
  'calendarizing',
  'bulletting',
  'boxing',
] as const satisfies readonly LoaderStateName[];

const atmosphereStates = [
  'glimmering',
  'radiating',
  'harmonizing',
  'twinkling',
  'flickering',
  'shimmering',
  'surfacing',
  'vibrating',
  'illuminating',
  'sparkling',
  'raining',
] as const satisfies readonly LoaderStateName[];

const categorizedStates = new Set<LoaderStateName>([
  ...loaderStates,
  ...systemStates,
  ...dataStates,
  ...reasoningStates,
  ...atmosphereStates,
]);

/** Public category metadata. Every state appears exactly once. */
export const LOADER_CATEGORIES = Object.freeze([
  Object.freeze({ id: 'loaders' as const, label: 'Loaders', states: Object.freeze([...loaderStates]) }),
  Object.freeze({ id: 'systems' as const, label: 'Systems', states: Object.freeze([...systemStates]) }),
  Object.freeze({ id: 'data' as const, label: 'Data visualizations', states: Object.freeze([...dataStates]) }),
  Object.freeze({ id: 'reasoning' as const, label: 'Reasoning', states: Object.freeze([...reasoningStates]) }),
  Object.freeze({ id: 'atmosphere' as const, label: 'Atmosphere', states: Object.freeze([...atmosphereStates]) }),
  Object.freeze({
    id: 'motion' as const,
    label: 'Motion studies',
    states: Object.freeze(LOADER_STATES.filter((state) => !categorizedStates.has(state))),
  }),
] satisfies readonly LoaderCategory[]);
