import type { OrbMode, OrbState } from './types';

/** A semantic state name that has a matching direct import entry point. */
export type LoaderStateName = Exclude<OrbState, OrbMode>;

/**
 * Single source of truth for the public state names and their pure geometry builders.
 *
 * The runtime resolver, demo metadata, direct-entry verification and future documentation
 * generation all derive from this registry rather than maintaining independent state lists.
 */
export const STATE_TO_MODE: Record<LoaderStateName, OrbMode> = {
  working: 'orbit',
  searching: 'scan',
  connecting: 'network',
  weaving: 'weave',
  shaping: 'morph',
  listening: 'wave',
  breathing: 'pulse',
  composing: 'ribbon',
  solving: 'cube',
  observing: 'halo',
  dreaming: 'tunnel',
  charging: 'swarm',
  flowing: 'knot',
  awakening: 'nova',
  coding: 'circuit',
  transcending: 'portal',
  singing: 'aurora',
  growing: 'helix',
  blooming: 'flower',
  wandering: 'fireflies',
  decoding: 'matrix',
  calibrating: 'gyroscope',
  attracting: 'magnet',
  shattering: 'shards',
  crystallizing: 'crystal',
  constellating: 'constellation',
  folding: 'origami',
  echoing: 'echo',
  balancing: 'mobile',
  weathering: 'vortex',
  mapping: 'atlas',
  forging: 'forge',
  orbiting: 'satellites',
  racing: 'comet',
  bubbling: 'bubbles',
  spinning: 'pinwheel',
  electrifying: 'plasma',
  flocking: 'flock',
  throbbing: 'beats',
  cascading: 'cascade',
  spiraling: 'galaxy',
  juggling: 'juggle',
  eclipsing: 'eclipse',
  resonating: 'resonance',
  condensing: 'condense',
  dispersing: 'disperse',
  prisming: 'prism',
  levitating: 'levitate',
  synchronizing: 'synchronize',
  unraveling: 'unravel',
  pondering: 'lattice',
  deducing: 'deduce',
  branching: 'branch',
  focusing: 'aperture',
  reflecting: 'mirror',
  weighing: 'scales',
  recalling: 'memory',
  tracing: 'trace',
  converging: 'converge',
  questioning: 'query',
  glimmering: 'glimmer',
  radiating: 'radiance',
  harmonizing: 'harmony',
  twinkling: 'twinkle',
  flickering: 'flicker',
  shimmering: 'shimmer',
  surfacing: 'surface',
  vibrating: 'vibrate',
  illuminating: 'illuminate',
  sparkling: 'sparkle',
  loading: 'spinner',
  buffering: 'buffer',
  typing: 'ellipsis',
  processing: 'process',
  synthesizing: 'reason',
  considering: 'consider',
  uploading: 'upload',
  queuing: 'queue',
  associating: 'associate',
  evaluating: 'evaluate',
  reasoning: 'cognition',
  exploring: 'explore',
  linking: 'link',
  resolving: 'resolve',
  imagining: 'imagine',
};

/** Ordered semantic state names used by consumers that need to enumerate the full library. */
export const LOADER_STATES = Object.freeze(Object.keys(STATE_TO_MODE) as LoaderStateName[]);
